segmentize workflow

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -56,41 +56,42 @@ jobs:
           # copy ccache dir within QGIS source so it can be accessed from docker
           cp -r ~/.ccache/. ./.ccache_image_build
 
-          echo "##[group] QGIS deps Docker pull/rebuild"
-          cd .docker
-          docker --version
-          docker pull "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" || true
-          docker build --cache-from "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" -t "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" -f ${DOCKER_BUILD_DEPS_FILE} .
-          echo "push to qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}"
-          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
-          docker push "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}"
-          echo "##[endgroup]"
+        - name: QGIS deps Docker pull/rebuild
+          run: |
+            cd .docker
+            docker --version
+            docker pull "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" || true
+            docker build --cache-from "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" -t "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}" -f ${DOCKER_BUILD_DEPS_FILE} .
+            echo "push to qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}"
+            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
+            docker push "qgis/qgis3-build-deps:${DOCKER_DEPS_TAG}"
 
-          echo "##[group] Docker QGIS build"
-          DOCKER_BUILD_ARGS="--build-arg DOCKER_DEPS_TAG --build-arg CC --build-arg CXX"
-          docker build ${DOCKER_BUILD_ARGS} \
-                       --cache-from "qgis/qgis:${DOCKER_TAG}" \
-                       -t "qgis/qgis:BUILDER" \
-                       -f qgis.dockerfile ..
-          echo "##[endgroup]"
+        - name: Docker QGIS build
+          run: |
+            DOCKER_BUILD_ARGS="--build-arg DOCKER_DEPS_TAG --build-arg CC --build-arg CXX"
+            docker build ${DOCKER_BUILD_ARGS} \
+                         --cache-from "qgis/qgis:${DOCKER_TAG}" \
+                         -t "qgis/qgis:BUILDER" \
+                         -f qgis.dockerfile ..
 
-          echo "##[group] Tag container and copy cache"
-          docker run --name qgis_container qgis/qgis:BUILDER /bin/true
-          docker cp qgis_container:/QGIS/build_exit_value ./build_exit_value
+        - name: Tag container and copy cache
+          run: |
+            docker run --name qgis_container qgis/qgis:BUILDER /bin/true
+            docker cp qgis_container:/QGIS/build_exit_value ./build_exit_value
 
-          if [[ $(cat ./build_exit_value) != "OK" ]]; then
-            echo "Build failed, not pushing image"
-            exit 1
-          fi
+            if [[ $(cat ./build_exit_value) != "OK" ]]; then
+              echo "Build failed, not pushing image"
+              exit 1
+            fi
 
-          echo "Copy build cache from Docker container to Travis cache directory"
-          rm -rf ~/.ccache/*
-          mkdir -p ~/.ccache
-          docker cp qgis_container:/QGIS/.ccache_image_build/. ~/.ccache
-          echo "Cache size: "$(du -sh ~/.ccache)
-          echo "##[endgroup]"
+            echo "Copy build cache from Docker container to Travis cache directory"
+            rm -rf ~/.ccache/*
+            mkdir -p ~/.ccache
+            docker cp qgis_container:/QGIS/.ccache_image_build/. ~/.ccache
+            echo "Cache size: "$(du -sh ~/.ccache)
 
-          echo "##[group] Finalize image"
+      - name: Finalize image
+        run: |
           # enable experimental features in Docker to squash
           echo '{ "experimental": true}' | sudo tee /etc/docker/daemon.json
           sudo service docker restart
@@ -99,19 +100,17 @@ jobs:
                      --squash \
                      -t "qgis/qgis:${DOCKER_TAG}" \
                      -f qgis.dockerfile ..
-          echo "##[endgroup]"
 
-          echo "##[group] Pushing image to docker hub"
+      - name: Pushing image to docker hub
+        run: |
           docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
           docker push "qgis/qgis:${DOCKER_TAG}"
-          echo "##[endgroup]"
 
       - name: Trigger PyQGIS API docs build for ${{ matrix.branch }}
         if: success()
         env:
           branch: ${{ matrix.branch }}
         run: |
-          echo "##[group] Trigger build of PyQGIS Documentation"
           body='{
             "ref": "master",
             "inputs": {"qgis_branch": "__QGIS_VERSION_BRANCH__"}
@@ -122,7 +121,6 @@ jobs:
             -H "Authorization: token ${GH_TOKEN}" \
             https://api.github.com/repos/qgis/pyqgis/actions/workflows/2246440/dispatches \
             -d "${body}"
-          echo "##[endgroup]"
 
 
 
