fix pre-commit call to use from/to-ref

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -52,13 +52,7 @@ jobs:
               fi
               HEAD_SHA=${{ github.sha }}
             fi
-            MODIFIED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA | tr '\n' ' ')
-            echo "Modified files: ${MODIFIED_FILES}"
-            if [ -n "$MODIFIED_FILES" ]; then
-                pre-commit run --files ${MODIFIED_FILES} || (echo "pre-commit failed. Attempting to auto-fix..." && exit 1)
-            else
-                echo "No modified files detected. Skipping pre-commit checks."
-            fi
+            pre-commit run --from-ref $BASE_SHA --to-ref $HEAD_SHA || (echo "pre-commit failed. Attempting to auto-fix..." && exit 1)
 
       - name: Auto-commit fixes
         if: failure() && github.event_name == 'push'
