expan

diff --git a/.github/workflows/pre-commit.yaml b/.github/workflows/pre-commit.yaml
--- a/.github/workflows/pre-commit.yaml
+++ b/.github/workflows/pre-commit.yaml
@@ -41,7 +41,7 @@ jobs:
               exit 1
             fi
             echo "Modified files: ${MODIFIED_FILES[@]}"
-            pre-commit run --files "${MODIFIED_FILES[@]}" || (echo "pre-commit failed. Attempting to auto-fix..." && exit 1)
+            pre-commit run --files ${MODIFIED_FILES[@]} || (echo "pre-commit failed. Attempting to auto-fix..." && exit 1)
 
       - name: Commit fixes
         if: failure()
