Avoid hardcoding distro version in file names

diff --git a/.github/workflows/write_failure_comment.yml b/.github/workflows/write_failure_comment.yml
--- a/.github/workflows/write_failure_comment.yml
+++ b/.github/workflows/write_failure_comment.yml
@@ -14,7 +14,7 @@ jobs:
     strategy:
       matrix:
         qt-version: [ 5, 6 ]
-        distro-version: ['24.10', '39']
+        distro: ['fedora', 'ubuntu']
 
     permissions:
       pull-requests: write
@@ -32,7 +32,7 @@ jobs:
                run_id: context.payload.workflow_run.id,
             });
             let matchArtifacts = allArtifacts.data.artifacts.filter((artifact) => {
-              return artifact.name == "test-results-${{ matrix.distro-version }}-qt${{ matrix.qt-version }}"
+              return artifact.name == "test-results-${{ matrix.distro }}-qt${{ matrix.qt-version }}"
             });
             if (matchArtifacts.length>0)
             {
@@ -43,7 +43,7 @@ jobs:
                  archive_format: 'zip',
               });
               let fs = require('fs');
-              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test-results-${{ matrix.distro-version }}-qt${{ matrix.qt-version }}.zip`, Buffer.from(download.data));
+              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test-results-${{ matrix.distro }}-qt${{ matrix.qt-version }}.zip`, Buffer.from(download.data));
               core.setOutput('artifact_id', matchArtifacts[0].id);
             }
             else
@@ -53,7 +53,7 @@ jobs:
 
       - name: 'Unzip artifact'
         if: fromJSON(steps.download_artifact.outputs.artifact_id) > 0
-        run: unzip -j test-results-${{ matrix.distro-version }}-qt${{ matrix.qt-version }}.zip *.md pr_number git_commit || ( e=$? && if [ $e -ne 11 ]; then exit $e; fi )
+        run: unzip -j test-results-${{ matrix.distro }}-qt${{ matrix.qt-version }}.zip *.md pr_number git_commit || ( e=$? && if [ $e -ne 11 ]; then exit $e; fi )
 
       - name: 'Post test report markdown summary as comment on PR'
         if: fromJSON(steps.download_artifact.outputs.artifact_id) > 0
@@ -72,7 +72,7 @@ jobs:
                 issue_number: issue_number,
               });
 
-              const PREFIX = "# Tests failed for Qt ${{ matrix.qt-version }} (${{ matrix.distro-version }})";
+              const PREFIX = "# Tests failed for Qt ${{ matrix.qt-version }} (${{ matrix.distro }})";
 
               let body = PREFIX + "\n\n";
               body += "*One or more tests failed using the build from commit " + git_sha + "*\n\n";
